# Generated by Django 3.2.16 on 2023-03-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxymodelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('phone', models.BigIntegerField(blank=True)),
                ('Address', models.TextField(max_length=50)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proxymodelapp.customer')),
            ],
        ),
    ]
