# Generated by Django 4.1 on 2023-03-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=50)),
                ('categoryname', models.CharField(choices=[('Books', 'Books'), ('Business', 'Business'), ('Education', 'Education'), ('Entertainment', 'Entertainment')], default='Books', max_length=20)),
                ('subcategoryname', models.CharField(max_length=50)),
                ('appsubcategory', models.CharField(choices=[('E-Reader', 'E-Reader'), ('Fiction', 'Fiction'), ('Non_Fiction', 'Non_Fiction'), ('Accounting', 'Accounting'), ('CRM', 'CRM'), ('Database', 'Database'), ('Desgin', 'Desgin'), ('Development', 'Development'), ('Language', 'Language'), ('SocialMedia', 'SocialMedia')], default='E-Reader', max_length=20)),
                ('points', models.IntegerField()),
                ('Screenshot', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
