# Generated by Django 3.2.16 on 2023-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='appsubcategory',
            field=models.CharField(choices=[('EReader', 'EReader'), ('Fiction', 'Fiction'), ('NonFiction', 'NonFiction'), ('Accounting', 'Accounting'), ('CRM', 'CRM'), ('Database', 'Database'), ('Desgin', 'Desgin'), ('Development', 'Development'), ('Language', 'Language'), ('SocialMedia', 'SocialMedia')], default='EReader', max_length=20),
        ),
    ]
