# Generated by Django 3.2.16 on 2023-03-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_appsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Screenshot',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
