# Generated by Django 3.2.16 on 2023-03-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxymodelapp', '0001_initial'),
        ('api', '0004_alter_task_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.OneToOneField(blank=True, default=223, on_delete=django.db.models.deletion.CASCADE, to='proxymodelapp.customer'),
            preserve_default=False,
        ),
    ]
