# Generated by Django 3.2.16 on 2023-03-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxymodelapp', '0001_initial'),
        ('api', '0005_task_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proxymodelapp.customer'),
        ),
    ]
